---
title: "Investigating Brand Reputation of America's Top 100 Companies"
subtitle: "Proposal"
format: html
editor: visual
---

```{r}
library(dplyr)
library(ggplot2)
library(patchwork)
library(tidyverse)
library(ggrepel)
library(viridis)
library(ggpubr)
library(ggpmisc)
library(ggcorrplot)
```

```{r}
poll <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-31/poll.csv') 
reputation <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-31/reputation.csv')
```

Steps:
- Create summary of score variables to see which two attributes are highest on average
- Plot those two attributes

```{r}
average_attributes <- reputation %>%
  group_by(name) %>%
  summarise(average_score = mean(score), .groups ="drop") %>%
  arrange(desc(average_score))

average_attributes

```

The two highest attributes are vision and growth, so we will compare those in the next visualization. 

```{r}

reputation_v_g <- reputation %>%
  filter(name == "VISION" | name == "GROWTH") %>%
  select(company, name, score, industry)

reputation_v_g <- reputation_v_g %>%
  pivot_wider(
    names_from = name,
    values_from = score
  )

```

```{r}
ggplot(data = reputation_v_g,
       aes(x = VISION, y = GROWTH)) +
  geom_point(aes(color = industry)) +
  geom_smooth(method = lm) + 
#  geom_bin2d(binwidth = c(1, 1)) +
  stat_cor() +  
#  geom_rug() +
#  geom_text_repel(aes(label = company)) + 
# scale_color_viridis(discrete = TRUE) +
  theme_minimal() + 
  labs(
    x = "Vision Attribute (out of 100)",
    y = "Growth Attribute (out of 100)",
    title = "Comparison of Companies' Vision and Growth Ratings",
    subtitle = "Vision and growth are strongly correlated"
  )
```

```{r}
ggplot(data = reputation_v_g,
       aes(x = VISION, y = GROWTH)) +
#  geom_point(aes(color = industry)) +
  geom_smooth(method = lm) + 
  geom_bin2d() +
#  stat_cor() +  
#  geom_rug() +
#  geom_text_repel(aes(label = company)) + 
# scale_color_viridis(discrete = TRUE) +
  theme_minimal() + 
  labs(
    x = "Vision Attribute (out of 100)",
    y = "Growth Attribute (out of 100)",
    title = "Comparison of Companies' Vision and Growth Ratings",
    subtitle = "Vision and growth are strongly correlated"
  )
```

Correlation matrix:

```{r}
reputation_longer <- reputation %>%
  select(company, name, score, industry) %>%
  pivot_wider(
    names_from = name,
    values_from = score
  )

```

```{r}
attributes_corr <- reputation_longer %>%
  as.data.frame() %>%                
  select(TRUST, ETHICS, GROWTH, `P&S`, CITIZENSHIP, VISION, CULTURE) %>%                   
  as.matrix() %>%                   
  cor() 
attributes_corr

attributes_p_values <- cor_pmat(attributes_corr)
attributes_p_values
```

```{r}
ggcorrplot(attributes_corr, 
           hc.order = TRUE, 
           outline.col = "white",
           method = "circle",
           p.mat = attributes_p_values,
           colors = c("#6D9EC1", "white", "#E46726"))
```











